<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LoginEnter your password to login91-807_ace65a</name>
   <tag></tag>
   <elementGuidId>ad264151-96a1-4b20-a891-ba3aeb1246aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container.h-100.d-flex.align-items-center.justify-content-center.flex-column.px-sm-2.px-md-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aefbd220-2f2d-4645-a1f2-27fdbe17b823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container h-100 d-flex align-items-center justify-content-center flex-column px-sm-2 px-md-0</value>
      <webElementGuid>06f98af7-5a0f-42c0-b93e-deb72a7f94b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginEnter your password to login+91-8072536860EditStay Signed InForgot Password?LoginOrLogin with OTP</value>
      <webElementGuid>12f72b13-82dc-403f-9449-2f1227076f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;px-0 mx-0 col-sm-12 col-lg-4 col-md-6 text-center d-flex flex-column align-items-center justify-content-center&quot;]/div[@class=&quot;max-width-restrict px-4 p-2 mb-3&quot;]/div[1]/div[@class=&quot;container h-100 d-flex align-items-center justify-content-center flex-column px-sm-2 px-md-0&quot;]</value>
      <webElementGuid>010d0e65-1de2-4635-af46-22c4a2bf4282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>a8856475-0ddf-4a93-a591-fb74760ae00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available On'])[1]/following::div[9]</value>
      <webElementGuid>21c01b91-fd91-44c6-a9f6-e7c4c746424b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick access to exclusive content'])[1]/following::div[10]</value>
      <webElementGuid>660b8894-15ea-40f8-a54b-b628eaa9dc48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>111718d4-5a8a-43d5-a7a1-58be086674a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoginEnter your password to login+91-8072536860EditStay Signed InForgot Password?LoginOrLogin with OTP' or . = 'LoginEnter your password to login+91-8072536860EditStay Signed InForgot Password?LoginOrLogin with OTP')]</value>
      <webElementGuid>8596cf53-1b61-4d4e-932f-cb3d98422c61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
