<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>157e9153-b6ea-4d6e-acce-44d5954486b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div[3]/div[3]/div/div[2]/span[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dacc3aca-b936-4491-84a3-f4face860ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAABAAAAEKADAAQAAAABAAAAEAAAAAAXnVPIAAAAn0lEQVQ4EWNgGAWMoCD4n7Fc4SfD3/mkBAcj4/+J7NNjN7CANDHOiHzwI3PJRsb//wWINYTtP8sFYtXiVQf2AkwFyCu/GP/0///PiNMlzAz/G1lnxB6A6QF7AcYB0/8ZGRkY/6MYjCqPwqOcg9Wm/wnzBX5xsOUjG8/IxLCRbVo0RsBhegGo6w8Hi8F/xn+OyAYAw+UjkI9hALKakcoGAHj1KrgXaoDSAAAAAElFTkSuQmCC</value>
      <webElementGuid>a00705cb-44dc-4396-a2dc-ca10a502e678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row m-0&quot;]/div[@class=&quot;side-menu&quot;]/div[@class=&quot;wrap-all-the-things&quot;]/div[@class=&quot;col-12 px-0&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row dashboard-container m-0&quot;]/div[@class=&quot;col-lg-9 col-12 p-0 dashboard-left-container&quot;]/div[1]/div[@class=&quot;dashboard-appointments-view-table ml-3 mt-4 mr-3&quot;]/div[@class=&quot;dashboard-appointments-table-header&quot;]/div[@class=&quot;row header d-none d-sm-none d-md-flex&quot;]/div[@class=&quot;col-md-3 pl-3&quot;]/span[2]/img[1]</value>
      <webElementGuid>037456e8-e4b2-485e-a5b1-b5a221abd7cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div[3]/div[3]/div/div[2]/span[2]/img</value>
      <webElementGuid>ec1684aa-380e-41ab-b546-9246c4647d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAABAAAAEKADAAQAAAABAAAAEAAAAAAXnVPIAAAAn0lEQVQ4EWNgGAWMoCD4n7Fc4SfD3/mkBAcj4/+J7NNjN7CANDHOiHzwI3PJRsb//wWINYTtP8sFYtXiVQf2AkwFyCu/GP/0///PiNMlzAz/G1lnxB6A6QF7AcYB0/8ZGRkY/6MYjCqPwqOcg9Wm/wnzBX5xsOUjG8/IxLCRbVo0RsBhegGo6w8Hi8F/xn+OyAYAw+UjkI9hALKakcoGAHj1KrgXaoDSAAAAAElFTkSuQmCC')]</value>
      <webElementGuid>e76674dd-7d47-440c-b0f1-a743fa6b6a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/img</value>
      <webElementGuid>a980097d-dde1-4506-824e-bb56046bdbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAABAAAAEKADAAQAAAABAAAAEAAAAAAXnVPIAAAAn0lEQVQ4EWNgGAWMoCD4n7Fc4SfD3/mkBAcj4/+J7NNjN7CANDHOiHzwI3PJRsb//wWINYTtP8sFYtXiVQf2AkwFyCu/GP/0///PiNMlzAz/G1lnxB6A6QF7AcYB0/8ZGRkY/6MYjCqPwqOcg9Wm/wnzBX5xsOUjG8/IxLCRbVo0RsBhegGo6w8Hi8F/xn+OyAYAw+UjkI9hALKakcoGAHj1KrgXaoDSAAAAAElFTkSuQmCC']</value>
      <webElementGuid>b106757f-6557-40fc-ab16-ccf180cb167c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
