<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Male_patient_gender</name>
   <tag></tag>
   <elementGuidId>32e83acf-d251-466d-8716-ddb56410266e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Female</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Female']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb2fbead-b239-4c02-8b0c-d4184495e947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>0f4598b9-6f0e-4b2a-b45f-6e8fb9f3f437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1e1e07f4-dcd0-4264-b893-94927a26bd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>45f0df60-9cb7-4981-ac2a-bb373e39920f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>patient_gender</value>
      <webElementGuid>b91bcdc8-3136-4554-a4ed-a1d5e5221803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>944c2de5-3ff2-43cc-bc5b-dc2720c73318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Female&quot;)</value>
      <webElementGuid>6c105462-2f1d-4ea6-9ce6-258bace77d53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Female']</value>
      <webElementGuid>6560b296-e150-4d3b-88a5-f6cb671c10c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d203bccf-56d1-4d17-b2bf-e3d020e15023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'Female' and @name = 'patient_gender']</value>
      <webElementGuid>ab5c8f00-130d-4893-a54a-3e2c49b9467f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
