<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sex_patient_gender</name>
   <tag></tag>
   <elementGuidId>d4a99b35-dba0-4505-9452-7fe416288102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Male</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Male']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e598917-b3bd-462e-9cc5-8b4cbe6f730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f05c4fe2-d085-43bf-9bd5-ff973c9e23ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>906fcbec-44bc-4420-85e8-ebe787f982c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>3fd526d7-c79b-476b-87a3-5ac11c771a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>patient_gender</value>
      <webElementGuid>5171f22e-80ff-48a8-83da-cae224bcfbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>872d93d7-3d5e-4043-9832-e0c544204003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Male&quot;)</value>
      <webElementGuid>00c3a1ce-13eb-4b54-af92-15d0b0cbef12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Male']</value>
      <webElementGuid>4ce91e6c-c8a9-44e1-b6b3-e04a417a34ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>5da11c4e-3bbd-4436-9d3d-295716c81364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'Male' and @name = 'patient_gender']</value>
      <webElementGuid>1f778b36-6744-4e23-bb07-0d51446b6594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
