<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Raise Invoice</name>
   <tag></tag>
   <elementGuidId>65c433d9-597e-4d03-b9fd-3379427f056a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div[3]/div[4]/div/div[2]/div/div/span/div/div/div/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8518bbe5-b239-4df6-ae78-1b133e7610b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pl-2</value>
      <webElementGuid>6eb0f6fd-5439-4127-b67a-cb456c7b4fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Raise Invoice</value>
      <webElementGuid>70a51783-f84a-489e-b5f6-72bb317a0a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row m-0&quot;]/div[@class=&quot;side-menu&quot;]/div[@class=&quot;wrap-all-the-things&quot;]/div[@class=&quot;col-12 px-0&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;row dashboard-container m-0&quot;]/div[@class=&quot;col-lg-9 col-12 p-0 dashboard-left-container&quot;]/div[1]/div[@class=&quot;dashboard-appointments-view-table ml-3 mt-4 mr-3&quot;]/div[@class=&quot;appointments-view-table-cell&quot;]/div[1]/div[@class=&quot;dashboard-appointments-table-container&quot;]/div[@class=&quot;dashboard-appointments-table-content d-flex pb-2&quot;]/div[@class=&quot;d-flex align-items-center col-md-2 justify-content-end&quot;]/span[@class=&quot;d-flex align-items-center col-md-2 justify-content-end&quot;]/div[1]/div[@class=&quot;filter-menu-list transform-style-custom&quot;]/div[@class=&quot;dropdown&quot;]/div[3]/div[@class=&quot;filter-menu-list-item&quot;]/span[@class=&quot;pl-2&quot;]</value>
      <webElementGuid>fe013984-69b9-475a-8ee3-f8e9111a7446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div[3]/div[4]/div/div[2]/div/div/span/div/div/div/div[3]/div/span</value>
      <webElementGuid>7e57ff60-36a9-4f6c-b192-2cd357d7f699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Vitals'])[1]/following::span[1]</value>
      <webElementGuid>c8825c8a-b97a-4f52-ae1b-4e1d3e7e7911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Follow-up'])[1]/following::span[2]</value>
      <webElementGuid>ff2ddb4a-6e3f-4fea-8d53-06f52c8eddea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Prescription'])[1]/preceding::span[1]</value>
      <webElementGuid>7aa7009f-b21c-4d65-891e-1c18c794a027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Raise Invoice']/parent::*</value>
      <webElementGuid>c59687ec-3993-4aff-b079-1008af9e0f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div[3]/div/span</value>
      <webElementGuid>62393cac-65a8-46f5-941a-a678c7a3fa82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Raise Invoice' or . = 'Raise Invoice')]</value>
      <webElementGuid>6e3ffbf0-550c-4520-9d09-d9800a29e235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
