version: 2.1
orbs:
    katalon-studio: katalon/katalon-studio@23.0.11
    
workflows:
  build:
    jobs:
        - katalon-studio/run:
                version: "latest"
                command_arguments: '-browserType="Chrome" -retry=2 -statusDelay=15 -testSuitePath="Test Suites/C2C_BookAppointment_E2E_Flow"'
